### ISSUE TITLE
TypeError: colors.bgblack is not a function in liferay-theme-tasks/lib/upgrade/7.0/upgrade.js:482:30)

### ISSUE THREAD

**Issue by maartenl** [liferay/liferay-themes-sdk#125]
Steps to reproduce:
- yo liferay-theme
- choose version 7.0
- gulp kickstart
- choose Classic
- gulp upgrade

I receive the following error:
[07:16:57] Error: something went wrong during the upgrade task, reverting changes.
[07:16:57] { TypeError: colors.bgblack is not a function
    at logBuffer (/home/maartenl/theme70/karchan-theme/node_modules/liferay-theme-tasks/lib/upgrade/7.0/upgrade.js:482:30)
    at Gulp.<anonymous> (/home/maartenl/theme70/karchan-theme/node_modules/liferay-theme-tasks/lib/upgrade/7.0/upgrade.js:174:3)
    at module.exports (/home/maartenl/theme70/karchan-theme/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/maartenl/theme70/karchan-theme/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/maartenl/theme70/karchan-theme/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/maartenl/theme70/karchan-theme/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/maartenl/theme70/karchan-theme/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/home/maartenl/theme70/karchan-theme/node_modules/run-sequence/index.js:75:5)
    at Gulp.emit (events.js:187:15)
    at Gulp.Orchestrator._emitTaskDone (/home/maartenl/theme70/karchan-theme/node_modules/orchestrator/index.js:264:8)
    at /home/maartenl/theme70/karchan-theme/node_modules/orchestrator/index.js:275:23
    at finish (/home/maartenl/theme70/karchan-theme/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/home/maartenl/theme70/karchan-theme/node_modules/orchestrator/lib/runTask.js:29:3)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

(if I comment out the line in the upgrade.js file, the upgrade completes without problems, but I don't know what that breaks...)

**Comment by jbalsas** [comment]
Thanks for reporting, @maartenl, I think the `colors` dependency must have updated, which now brings `bgBlack` instead. We [fixed this in 8.x.x](https://github.com/liferay/liferay-themes-sdk/commit/1736b8ad58da0d35ca3cbce3c299cebf966f722f) but forgot to do it in `7.x.x`. We'll look into this asap.

**Comment by jbalsas** [comment]
Should be fixed in `8.0.0-rc.2` that we're about to release!

**Comment by brhane87** [comment]
I'm using 8.1.1 but still getting the same exception. 
Here is what I did 
      1. npm install --save-dev liferay-theme-tasks@8.x.x 
      2. gulp upgrade
I tried the lower version 8.0.9 but still getting the same error.
